# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0003_business_timestamp'),
        ('users', '0003_auto_20190606_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoods.Business'),
        ),
    ]
