# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-06 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoods',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
